### ISSUE TITLE
Assembly issue

### ISSUE THREAD

**Issue by syepes** [wasted/netflow#9]
Hello,

I would like to test this project but I am currently getting the following build issue. Do you know how I can resole this problem?

sbt.cmd assembly
```
[info] Including joda-convert-1.2.jar
[info] Including slf4j-api-1.6.6.jar
[info] Including scala-library.jar
[info] Merging 'META-INF\MANIFEST.MF' with strategy 'deduplicate'
java.lang.RuntimeException: deduplicate: different file contents found in the following:
D:\Users\s\.ivy2\cache\ch.qos.logback\logback-classic\jars\logback-classic-1.0.7.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\ch.qos.logback\logback-core\jars\logback-core-1.0.7.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.github.spullara.cli-parser\cli-parser\jars\cli-parser-1.1.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.github.spullara.redis\client\jars\client-0.3.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.github.spullara.redis\protocol\jars\protocol-0.3.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.github.spullara.redis\util\jars\util-0.3.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.google.code.findbugs\jsr305\jars\jsr305-1.3.9.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.google.guava\guava\jars\guava-12.0.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.jcraft\jzlib\jars\jzlib-1.1.2.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\com.typesafe\config\bundles\config-0.6.0.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\commons-codec\commons-codec\jars\commons-codec-1.7.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\io.netty\netty-all\jars\netty-all-4.0.0.CR1.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\io.wasted\wasted-util_2.10\jars\wasted-util_2.10-0.5.0-SNAPSHOT.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\joda-time\joda-time\jars\joda-time-2.1.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\org.joda\joda-convert\jars\joda-convert-1.2.jar:META-INF/MANIFEST.MF
D:\Users\s\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.6.6.jar:META-INF/MANIFEST.MF
D:\Users\s\.sbt\boot\scala-2.10.0\lib\scala-library.jar:META-INF/MANIFEST.MF
        at sbtassembly.Plugin$$anonfun$sbtassembly$Plugin$$assemblyTask$1$$anonfun$8.apply(Plugin.scala:166)
        at sbtassembly.Plugin$$anonfun$sbtassembly$Plugin$$assemblyTask$1$$anonfun$8.apply(Plugin.scala:157)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:178)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:347)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:347)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:347)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:239)
        at scala.collection.immutable.HashMap.flatMap(HashMap.scala:38)
        at sbtassembly.Plugin$$anonfun$sbtassembly$Plugin$$assemblyTask$1.apply(Plugin.scala:169)
        at sbtassembly.Plugin$$anonfun$sbtassembly$Plugin$$assemblyTask$1.apply(Plugin.scala:138)
        at sbt.IO$.withTemporaryDirectory(IO.scala:281)
        at sbtassembly.Plugin$.sbtassembly$Plugin$$assemblyTask(Plugin.scala:138)
        at sbtassembly.Plugin$$anonfun$baseAssemblySettings$4.apply(Plugin.scala:262)
        at sbtassembly.Plugin$$anonfun$baseAssemblySettings$4.apply(Plugin.scala:261)
        at sbt.Scoped$$anonfun$hf7$1.apply(Structure.scala:583)
        at sbt.Scoped$$anonfun$hf7$1.apply(Structure.scala:583)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] D:\Users\s\.ivy2\cache\ch.qos.logback\logback-classic\jars\logback-classic-1.0.7.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\ch.qos.logback\logback-core\jars\logback-core-1.0.7.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.github.spullara.cli-parser\cli-parser\jars\cli-parser-1.1.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.github.spullara.redis\client\jars\client-0.3.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.github.spullara.redis\protocol\jars\protocol-0.3.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.github.spullara.redis\util\jars\util-0.3.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.google.code.findbugs\jsr305\jars\jsr305-1.3.9.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.google.guava\guava\jars\guava-12.0.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.jcraft\jzlib\jars\jzlib-1.1.2.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\com.typesafe\config\bundles\config-0.6.0.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\commons-codec\commons-codec\jars\commons-codec-1.7.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\io.netty\netty-all\jars\netty-all-4.0.0.CR1.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\io.wasted\wasted-util_2.10\jars\wasted-util_2.10-0.5.0-SNAPSHOT.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\joda-time\joda-time\jars\joda-time-2.1.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\org.joda\joda-convert\jars\joda-convert-1.2.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.6.6.jar:META-INF/MANIFEST.MF
[error] D:\Users\s\.sbt\boot\scala-2.10.0\lib\scala-library.jar:META-INF/MANIFEST.MF
[error] Total time: 246 s, completed 9 avr. 2013 23:03:44
```

Regards and thanks for any help.

**Comment by fbettag** [comment]
Closed due to inactivity. I guess the issue is long gone.
